# Generated by Django 6.0.1 on 2026-01-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
